# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f200e91946f40c564cdb811a7cf307999bb63374fad914b19530c1dde6949229153d33a8a49931d74c71b156fb2b7cf4f422c0b473703bf28ea17cd0bcfd8d73

test:
  secret_key_base: 71e9f12486165583a31f76c491e8b3fe43993c902a3628ed7d4262c1d25638019b43228262f9999450fafac611f20d7f5ce6270d81474bb8ec1b827f67bb3b59

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
